---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: git-assets

outputs:
- name: app-output

run:
  path: git-assets/concourse-workshop/ci/tasks/package.sh
